### ISSUE TITLE
inconsistent naming

### ISSUE THREAD

**Issue by jronallo** [NCSU-Libraries/quick_search-generic_theme#1]
I think this could be an issue. The name of the repo is quick_search-generic_theme but the library is named quicksearch_generic_theme and the value to put in the config for the theme is quicksearch_generic_theme. I'm not sure the best way to resolve this.

Maybe we always need to refer to use quick_search to avoid confusion?

**Comment by kbeswick** [comment]
fixed this in 0438b137938d1dd, I think we've talked about this in person too since you opened this
