### ISSUE TITLE
update documentation for how to install generic theme in application

### ISSUE THREAD

**Issue by jronallo** [NCSU-Libraries/quick_search-generic_theme#3]
I've added the following to my Gemfile which seems to be what is currently necessary before a release to Rubygems. If this is correct it ought to be added to the README.

```
gem 'quicksearch_generic_theme', git: 'git@github.com:NCSU-Libraries/quick_search-generic_theme.git'
```

**Comment by kbeswick** [comment]
fixed in 0377a41
