### ISSUE TITLE
uninitialized constant QuickSearchGeneric Theme

### ISSUE THREAD

**Issue by jronallo** [NCSU-Libraries/quick_search-generic_theme#4]
Once I install the gem I get this error: `uninitialized constant QuickSearchGeneric Theme` which I think is because the module has a different name than that:

https://github.com/NCSU-Libraries/quick_search-generic_theme/blob/master/lib/quicksearch_generic_theme.rb#L3

**Comment by kbeswick** [comment]
I pushed a change since you have opened this issue that fixes this. I pushed similar changes to all the other searcher gems too to update naming to reflect the new QuickSearch / quick_search naming scheme.
